In [480]:
import pandas as pd
import numpy as np
import datetime as dt

In [481]:
bout_sum_csv = "bout_summary.csv"
fighter_csv = "fighter_data.csv"

In [482]:
bout_df = pd.read_csv(bout_sum_csv)
bout_df.head()

,fight_id,fighter_1,fighter_1_id,fighter_2,fighter_2_id,winner,decision_method,fight_duration_lastrnd,fight_duration_lastrnd_time,time_format,weight_class,date,location
0,d7cbe2f23d75afd1,Julio Arce,1291edf2d566a71a,Hakeem Dawodu,2c9d00968f818270,Hakeem Dawodu,Decision - Split,3,5:00,3 Rnd (5-5-5),Featherweight Bout,"November 02, 2019","New York City, New York, USA"
1,f0418c2c989a5cde,Grigorii Popov,d3fa5c5955397532,Davey Grant,113df4fde64735c6,Davey Grant,Decision - Split,3,5:00,3 Rnd (5-5-5),Bantamweight Bout,"November 09, 2019","Moscow, Moscow, Russia"
2,fc16ccf0994c6e50,Jack Shore,b8a85389d115e35a,Nohelin Hernandez,f97c5433c77522d3,Jack Shore,Submission,3,2:51,3 Rnd (5-5-5),Bantamweight Bout,"September 28, 2019","Copenhagen, Denmark"
3,18e1b0df8da7010e,Vanessa Melo,9b7dfb3b7d99926a,Tracy Cortez,68d4a891e5cf2029,Tracy Cortez,Decision - Unanimous,3,5:00,3 Rnd (5-5-5),Women's Bantamweight Bout,"November 16, 2019","Sao Paulo, Sao Paulo, Brazil"
4,57ff0eb2351979c4,Khalid Taha,b4537562f88ac582,Bruno Silva,294aa73dbf37d281,Khalid Taha,Submission,3,3:00,3 Rnd (5-5-5),Bantamweight Bout,"October 05, 2019","Melbourne, Victoria, Australia"

In [483]:
## List of transformations to be performed

# remove fighter id columns from the dataset
# drop any fights with an unlimited time limit
# drop location data, it will not be used in this project

bout_df = bout_df[["fight_id","fighter_1", "fighter_2", "winner", "decision_method", "fight_duration_lastrnd", "fight_duration_lastrnd_time",
                 "time_format", "weight_class", "date"]]

In [484]:
bout_df["time_format"].unique()

array(['3 Rnd (5-5-5)', 'No Time Limit', '5 Rnd (5-5-5-5-5)',
       '1 Rnd (20)', '1 Rnd (15)', '1 Rnd + OT (12-3)', '1 Rnd (10)',
       '1 Rnd + 2OT (15-3-3)', '1 Rnd + 2OT (24-3-3)',
       '1 Rnd + OT (15-3)', '1 Rnd (18)', '1 Rnd + OT (27-3)',
       '1 Rnd + OT (30-3)', '1 Rnd + OT (30-5)', '1 Rnd + OT (31-5)',
       '1 Rnd (30)', '1 Rnd (12)', '2 Rnd (5-5)', '3 Rnd + OT (5-5-5-5)'],
      dtype=object)

In [485]:
bout_df = bout_df.drop(bout_df.index[bout_df["time_format"] != '3 Rnd (5-5-5)'])
bout_df

,fight_id,fighter_1,fighter_2,winner,decision_method,fight_duration_lastrnd,fight_duration_lastrnd_time,time_format,weight_class,date
0,d7cbe2f23d75afd1,Julio Arce,Hakeem Dawodu,Hakeem Dawodu,Decision - Split,3,5:00,3 Rnd (5-5-5),Featherweight Bout,"November 02, 2019"
1,f0418c2c989a5cde,Grigorii Popov,Davey Grant,Davey Grant,Decision - Split,3,5:00,3 Rnd (5-5-5),Bantamweight Bout,"November 09, 2019"
2,fc16ccf0994c6e50,Jack Shore,Nohelin Hernandez,Jack Shore,Submission,3,2:51,3 Rnd (5-5-5),Bantamweight Bout,"September 28, 2019"
3,18e1b0df8da7010e,Vanessa Melo,Tracy Cortez,Tracy Cortez,Decision - Unanimous,3,5:00,3 Rnd (5-5-5),Women's Bantamweight Bout,"November 16, 2019"
4,57ff0eb2351979c4,Khalid Taha,Bruno Silva,Khalid Taha,Submission,3,3:00,3 Rnd (5-5-5),Bantamweight Bout,"October 05, 2019"
...,...,...,...,...,...,...,...,...,...,...
5438,953c89aa931082e4,Jose Quinonez,Carlos Huachin,Jose Quinonez,Decision - Unanimous,3,5:00,3 Rnd (5-5-5),Bantamweight Bout,"September 21, 2019"
5439,c163ed45c21c8548,Irene Aldana,Vanessa Melo,Irene Aldana,Decision - Unanimous,3,5:00,3 Rnd (5-5-5),Women's Bantamweight Bout,"September 21, 2019"
5440,49b2a6a93d529981,Martin Bravo,Steven Peterson,Steven Peterson,KO/TKO,2,1:31,3 Rnd (5-5-5),Featherweight Bout,"September 21, 2019"
5441,fd3e8f61d8fda839,Brandon Moreno,Askar Askarov,Draw,Decision - Split,3,5:00,3 Rnd (5-5-5),Flyweight Bout,"September 21, 2019"
5442,b2cdb4c34f37ad37,Carla Esparza,Alexa Grasso,Carla Esparza,Decision - Majority,3,5:00,3 Rnd (5-5-5),Women's Strawweight Bout,"September 21, 2019"

In [486]:
new = bout_df["fight_duration_lastrnd_time"].str.split(":")

In [487]:
bout_df["fight_max_length"] = dt.timedelta(minutes=5) * bout_df["fight_duration_lastrnd"]

In [488]:
bout_end_times = []

for i in new:
    end_time = dt.timedelta(minutes=int(i[0]), seconds=int(i[1]))
    bout_end_times.append(end_time)
    
bout_df["bout_end_time"] = bout_end_times

In [489]:
fight_length = []

for i in bout_df["bout_end_time"]:
    j = 0
    if i == dt.timedelta(minutes=5):
        bout_length = bout_df["fight_max_length"][j].total_seconds()/60
        j = j + 1
        
    else:
        bout_length = bout_df["fight_max_length"][j] - i
        bout_length = bout_length.total_seconds()/60
        j = j + 1
    
    fight_length.append(bout_length)
    
bout_df["fight_length_min"] = fight_length

In [490]:
bout_df = bout_df.drop("fight_max_length", axis = 1)
bout_df = bout_df.drop("bout_end_time", axis=1)

In [491]:
new = bout_df["date"].str.split(",")    
years = []

for i in new:
    year = i[1]
    years.append(year)
    
bout_df["date"] = years

In [492]:
bout_df = bout_df.drop(["fighter_1", "fighter_2"], axis = 1)
bout_df

,fight_id,winner,decision_method,fight_duration_lastrnd,fight_duration_lastrnd_time,time_format,weight_class,date,fight_length_min
0,d7cbe2f23d75afd1,Hakeem Dawodu,Decision - Split,3,5:00,3 Rnd (5-5-5),Featherweight Bout,2019,15.000000
1,f0418c2c989a5cde,Davey Grant,Decision - Split,3,5:00,3 Rnd (5-5-5),Bantamweight Bout,2019,15.000000
2,fc16ccf0994c6e50,Jack Shore,Submission,3,2:51,3 Rnd (5-5-5),Bantamweight Bout,2019,12.150000
3,18e1b0df8da7010e,Tracy Cortez,Decision - Unanimous,3,5:00,3 Rnd (5-5-5),Women's Bantamweight Bout,2019,15.000000
4,57ff0eb2351979c4,Khalid Taha,Submission,3,3:00,3 Rnd (5-5-5),Bantamweight Bout,2019,12.000000
...,...,...,...,...,...,...,...,...,...
5438,953c89aa931082e4,Jose Quinonez,Decision - Unanimous,3,5:00,3 Rnd (5-5-5),Bantamweight Bout,2019,15.000000
5439,c163ed45c21c8548,Irene Aldana,Decision - Unanimous,3,5:00,3 Rnd (5-5-5),Women's Bantamweight Bout,2019,15.000000
5440,49b2a6a93d529981,Steven Peterson,KO/TKO,2,1:31,3 Rnd (5-5-5),Featherweight Bout,2019,13.483333
5441,fd3e8f61d8fda839,Draw,Decision - Split,3,5:00,3 Rnd (5-5-5),Flyweight Bout,2019,15.000000
5442,b2cdb4c34f37ad37,Carla Esparza,Decision - Majority,3,5:00,3 Rnd (5-5-5),Women's Strawweight Bout,2019,15.000000

In [346]:
fighter_df = pd.read_csv(fighter_csv)
fighter_df

,dob,fighter_id,height,n_draw,n_loss,n_win,name,reach,sig_str_abs_pM,sig_str_def_pct,sig_str_land_pM,sig_str_land_pct,stance,sub_avg,td_avg,td_def_pct,td_land_pct,weight
0,"Mar 02, 1992",2af2f2e26c4c0402,"5' 8""",0,0,8,Hunter Azure,"69""",1.57,0.56,4.00,0.50,Orthodox,2.5,2.00,0.75,0.33,135 lbs.
1,"Jul 27, 1986",f72465a784c1b084,"5' 6""",0,7,14,Jessica Eye,"66""",3.36,0.60,3.51,0.36,Orthodox,0.7,0.51,0.56,0.50,125 lbs.
2,"Aug 11, 1990",55ed59d541f8b90c,"5' 8""",1,7,9,Rolando Dy,"69""",4.47,0.52,3.04,0.37,Orthodox,0.0,0.30,0.68,0.20,145 lbs.
3,"Feb 07, 1989",44a94bbde42246e4,"5' 9""",0,3,7,Gleidson Cutis,--,8.28,0.59,2.99,0.52,Orthodox,0.0,0.00,0.00,0.00,155 lbs.
4,"Dec 25, 1984",d024ed963e8bf7ea,"5' 10""",0,12,17,Damien Brown,"68""",4.86,0.50,3.66,0.38,Orthodox,0.7,0.68,0.53,0.27,155 lbs.
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3391,"Jul 12, 1972",6014d25e73b669c9,"5' 11""",10,27,40,Keiichiro Yamamiya,--,0.00,0.00,0.00,0.00,Southpaw,0.0,0.00,0.00,0.00,185 lbs.
3392,"Jul 18, 1984",d06f8869449ba7bd,"6' 3""",1,9,24,Alexander Yakovlev,"74""",2.44,0.58,1.79,0.47,Southpaw,0.2,1.56,0.72,0.33,155 lbs.
3393,"Sep 12, 1984",94527830000ab715,"5' 6""",0,10,26,Rani Yahya,"67""",1.61,0.52,1.59,0.36,Orthodox,2.1,2.92,0.22,0.32,135 lbs.
3394,"Mar 23, 1979",cc84b68f862b466f,"5' 7""",1,5,16,Eddie Yagin,--,5.77,0.42,3.13,0.30,Orthodox,1.0,0.00,0.62,0.00,145 lbs.
3395,"Nov 29, 1983",85248da6e9e2f7e7,"6' 1""",0,2,5,Jamie Yager,--,2.55,0.63,3.08,0.39,Orthodox,0.0,0.00,0.66,0.00,185 lbs.

In [347]:
## List of transformations to be performed

# remove fighter_id column, we need to use the index as the fighter id when dropping into postgresSql
# convert DOB column into datetime format for ease of use in later calculations
# create a total fights column which adds draws/losses/wins for a total
# check for duplicate fighter names and drop the fighter with the lowest number of total fights (more fights means more data for their stats)
# drop any fighter with null values or zeroes in the sig_str_abs_PM and other columns, zeroes or nulls here would indicate they have no fight data
# add a weightclass column alongside fighter weight
# check for null values in stance column and replace with "Orthodox", fighters with no stance will be assumed for now (i.e. right handed)

In [348]:
fighter_df = fighter_df.drop("fighter_id", axis=1)

In [349]:
fighter_df["total_fights"] = fighter_df["n_draw"] + fighter_df["n_loss"] + fighter_df["n_win"]

In [350]:
fighter_df = fighter_df.dropna(subset=['sig_str_abs_pM', 'sig_str_def_pct', 'sig_str_land_pM', 'sig_str_land_pct','dob'])

In [351]:
fighter_df = fighter_df.drop((fighter_df.index[fighter_df["dob"] == '--']))

In [352]:
fighter_df = fighter_df.drop((fighter_df.index[fighter_df["sig_str_abs_pM"] == 0]))

In [353]:
fighter_df = fighter_df.reset_index(drop=True)

In [354]:
new = fighter_df["dob"].str.split(",")    
years = []

for i in new:
    year = i[1]
    years.append(year)
    
fighter_df['dob'] = years

In [448]:
fighter_df

,dob,height,n_draw,n_loss,n_win,name,reach,sig_str_abs_pM,sig_str_def_pct,sig_str_land_pM,sig_str_land_pct,stance,sub_avg,td_avg,td_def_pct,td_land_pct,weight,total_fights
0,1992,"5' 8""",0,0,8,Hunter Azure,69,1.57,0.56,4.00,0.50,Orthodox,2.5,2.00,0.75,0.33,135 lbs.,8
1,1986,"5' 6""",0,7,14,Jessica Eye,66,3.36,0.60,3.51,0.36,Orthodox,0.7,0.51,0.56,0.50,125 lbs.,21
2,1990,"5' 8""",1,7,9,Rolando Dy,69,4.47,0.52,3.04,0.37,Orthodox,0.0,0.30,0.68,0.20,145 lbs.,17
3,1989,"5' 9""",0,3,7,Gleidson Cutis,--,8.28,0.59,2.99,0.52,Orthodox,0.0,0.00,0.00,0.00,155 lbs.,10
4,1984,"5' 10""",0,12,17,Damien Brown,68,4.86,0.50,3.66,0.38,Orthodox,0.7,0.68,0.53,0.27,155 lbs.,29
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2418,1989,"5' 5""",0,1,11,Xiaonan Yan,63,4.22,0.64,6.85,0.40,Orthodox,0.0,0.25,0.66,0.50,115 lbs.,12
2419,1984,"6' 3""",1,9,24,Alexander Yakovlev,74,2.44,0.58,1.79,0.47,Southpaw,0.2,1.56,0.72,0.33,155 lbs.,34
2420,1984,"5' 6""",0,10,26,Rani Yahya,67,1.61,0.52,1.59,0.36,Orthodox,2.1,2.92,0.22,0.32,135 lbs.,36
2421,1979,"5' 7""",1,5,16,Eddie Yagin,--,5.77,0.42,3.13,0.30,Orthodox,1.0,0.00,0.62,0.00,145 lbs.,22
2422,1983,"6' 1""",0,2,5,Jamie Yager,--,2.55,0.63,3.08,0.39,Orthodox,0.0,0.00,0.66,0.00,185 lbs.,7

In [475]:
fighter_df["dob"] = fighter_df["dob"].astype('int')
new = fighter_df["reach"].str.split('"')
reach = []
for i in new:
    x = i[0]
    reach.append(x)
fighter_df["reach"] = reach

fighter_df = fighter_df.replace({"stance": "--", "stance": "switch", "stance": "Sideways"}, "Orthodox")
fighter_df = fighter_df.replace({"stance": "Open Stance"}, "Southpaw")
fighter_df = fighter_df.replace({"stance": "Switch"}, "Orthodox")
values = {"stance": "Orthodox"}
fighter_df = fighter_df.fillna(value = values)

fighter_df = fighter_df.replace({"height": "--"}, "")
fighter_df = fighter_df.replace({"reach": "--"}, "")

In [477]:
fighter_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2423 entries, 0 to 2422
Data columns (total 18 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   dob               2423 non-null   int32
 1   height            2423 non-null   object
 2   n_draw            2423 non-null   int64
 3   n_loss            2423 non-null   int64
 4   n_win             2423 non-null   int64
 5   name              2423 non-null   object
 6   reach             2423 non-null   object
 7   sig_str_abs_pM    2423 non-null   float64
 8   sig_str_def_pct   2423 non-null   float64
 9   sig_str_land_pM   2423 non-null   float64
 10  sig_str_land_pct  2423 non-null   float64
 11  stance            2423 non-null   object
 12  sub_avg           2423 non-null   float64
 13  td_avg            2423 non-null   float64
 14  td_def_pct        2423 non-null   float64
 15  td_land_pct       2423 non-null   float64
 16  weight            2423 non-null   object
 17  total_fights      2423 non-null   int64
dtypes: float64(8), int32(1), int64(4), object(5)
memory usage: 331.4+ KB

In [356]:
bout_detail_df = pd.read_json('bout_data.jl', lines =True)
bout_detail_df

,fight_id,fighter_id,fighter_name,fighter_status,kd,n_pass,n_rev,n_sub,sig_str_abs,sig_str_att,...,distance_def,distance_land,clinch_abs,clinch_att,clinch_def,clinch_land,ground_abs,ground_att,ground_def,ground_land
0,d7cbe2f23d75afd1,"[1291edf2d566a71a, 2c9d00968f818270]","[Julio Arce, Hakeem Dawodu]","[L, W]","[0, 0]","[2, 0]","[0, 1]","[0, 0]","[55, 32]","[124, 139]",...,"[81, 88]","[28, 40]","[11, 4]","[8, 14]","[3, 4]","[4, 11]","[4, 0]","[0, 4]","[0, 0]","[0, 4]"
1,f0418c2c989a5cde,"[d3fa5c5955397532, 113df4fde64735c6]","[Grigorii Popov, Davey Grant]","[L, W]","[0, 0]","[1, 2]","[2, 1]","[0, 0]","[30, 35]","[88, 63]",...,"[25, 40]","[25, 27]","[0, 4]","[5, 2]","[2, 1]","[4, 0]","[3, 6]","[18, 9]","[6, 12]","[6, 3]"
2,fc16ccf0994c6e50,"[b8a85389d115e35a, f97c5433c77522d3]","[Jack Shore, Nohelin Hernandez]","[W, L]","[0, 0]","[11, 0]","[0, 1]","[1, 0]","[6, 46]","[92, 36]",...,"[28, 32]","[26, 4]","[2, 3]","[4, 4]","[2, 1]","[3, 2]","[0, 17]","[30, 0]","[0, 13]","[17, 0]"
3,18e1b0df8da7010e,"[9b7dfb3b7d99926a, 68d4a891e5cf2029]","[Vanessa Melo, Tracy Cortez]","[L, W]","[0, 0]","[0, 1]","[0, 0]","[0, 0]","[79, 40]","[125, 140]",...,"[57, 85]","[32, 46]","[12, 6]","[6, 12]","[0, 0]","[6, 12]","[21, 2]","[2, 25]","[4, 0]","[2, 21]"
4,57ff0eb2351979c4,"[b4537562f88ac582, 294aa73dbf37d281]","[Khalid Taha, Bruno Silva]","[W, L]","[1, 0]","[1, 1]","[0, 0]","[1, 0]","[20, 38]","[88, 50]",...,"[21, 43]","[19, 10]","[1, 6]","[7, 1]","[0, 1]","[6, 1]","[9, 13]","[19, 18]","[9, 6]","[13, 9]"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5438,953c89aa931082e4,"[36549928f90f1d36, 225def29ecfe0fc1]","[Jose Quinonez, Carlos Huachin]","[W, L]","[1, 0]","[2, 0]","[0, 0]","[0, 0]","[32, 60]","[117, 115]",...,"[79, 52]","[40, 30]","[0, 0]","[1, 2]","[2, 1]","[0, 0]","[2, 20]","[24, 4]","[2, 4]","[20, 2]"
5439,c163ed45c21c8548,"[578ef12674df1e6a, 9b7dfb3b7d99926a]","[Irene Aldana, Vanessa Melo]","[W, L]","[0, 0]","[0, 0]","[0, 0]","[0, 0]","[68, 125]","[333, 250]",...,"[182, 208]","[124, 68]","[0, 1]","[1, 0]","[0, 0]","[1, 0]","[0, 0]","[0, 0]","[0, 0]","[0, 0]"
5440,49b2a6a93d529981,"[9c44f290f5726d95, b93c06d09d1c4ac0]","[Martin Bravo, Steven Peterson]","[L, W]","[0, 1]","[0, 0]","[0, 0]","[0, 0]","[49, 86]","[199, 105]",...,"[52, 113]","[85, 46]","[1, 1]","[1, 2]","[1, 0]","[1, 1]","[2, 0]","[0, 5]","[3, 0]","[0, 2]"
5441,fd3e8f61d8fda839,"[792be9a24df82ed6, b1d19449397541dc]","[Brandon Moreno, Askar Askarov]","[D, D]","[1, 0]","[1, 4]","[1, 1]","[0, 0]","[30, 34]","[82, 63]",...,"[30, 37]","[18, 9]","[4, 2]","[2, 4]","[0, 0]","[2, 4]","[17, 14]","[25, 20]","[3, 11]","[14, 17]"
5442,b2cdb4c34f37ad37,"[d910665038efc639, e8b731feff72294b]","[Carla Esparza, Alexa Grasso]","[W, L]","[0, 0]","[1, 0]","[1, 1]","[0, 1]","[45, 44]","[80, 103]",...,"[54, 31]","[28, 34]","[3, 6]","[9, 6]","[3, 3]","[6, 3]","[8, 10]","[12, 9]","[1, 2]","[10, 8]"

In [357]:
## Transformations required

# identify unneccessary columns i.e remove
# 'fighter_id', 'n_pass', 'n_rev', 'total_strike_def', 'td_abs', 'td_def', 'head_abs', 'head_att', 'head_def','head_abs',
#       'head_att', 'head_def', 'head_land', 'body_abs', 'body_att', 'body_def',
#      'body_land', 'leg_abs', 'leg_att', 'leg_def', 'leg_land',
#       'distance_abs', 'distance_att', 'distance_def', 'distance_land',
#       'clinch_abs', 'clinch_att', 'clinch_def', 'clinch_land', 'ground_abs',
#       'ground_att', 'ground_def', 'ground_land' 
# spearate doubled up columns and break into fighter_1, fighter_2 columns for each, create a new dataframe for this to preserve raw data
# after new dataframe is created, further manipulation is required after joining the dataframe with bout duration
# convert remaining striking columns into averages and percentages over the duration of the bout to align with fighter stats

In [358]:
bout_detail_df = bout_detail_df.drop(['fighter_id', 'n_pass', 'n_rev', 'td_abs', 'td_def', 'head_abs', 'head_att', 'head_def','head_abs',
       'head_att', 'head_def', 'head_land', 'body_abs', 'body_att', 'body_def',
      'body_land', 'leg_abs', 'leg_att', 'leg_def', 'leg_land',
       'distance_abs', 'distance_att', 'distance_def', 'distance_land',
       'clinch_abs', 'clinch_att', 'clinch_def', 'clinch_land', 'ground_abs',
      'ground_att', 'ground_def', 'ground_land'], axis = 1)

In [359]:
bout_detail_df.info

<bound method DataFrame.info of               fight_id                     fighter_name fighter_status  \
0     d7cbe2f23d75afd1      [Julio Arce, Hakeem Dawodu]         [L, W]
1     f0418c2c989a5cde    [Grigorii Popov, Davey Grant]         [L, W]
2     fc16ccf0994c6e50  [Jack Shore, Nohelin Hernandez]         [W, L]
3     18e1b0df8da7010e     [Vanessa Melo, Tracy Cortez]         [L, W]
4     57ff0eb2351979c4       [Khalid Taha, Bruno Silva]         [W, L]
...                ...                              ...            ...
5438  953c89aa931082e4  [Jose Quinonez, Carlos Huachin]         [W, L]
5439  c163ed45c21c8548     [Irene Aldana, Vanessa Melo]         [W, L]
5440  49b2a6a93d529981  [Martin Bravo, Steven Peterson]         [L, W]
5441  fd3e8f61d8fda839  [Brandon Moreno, Askar Askarov]         [D, D]
5442  b2cdb4c34f37ad37    [Carla Esparza, Alexa Grasso]         [W, L]

          kd   n_sub sig_str_abs sig_str_att sig_str_def sig_str_land  \
0     [0, 0]  [0, 0]    [55, 32]  [124, 139]    [84, 92]     [32, 55]
1     [0, 0]  [0, 0]    [30, 35]    [88, 63]    [33, 53]     [35, 30]
2     [0, 0]  [1, 0]     [6, 46]    [92, 36]    [30, 46]      [46, 6]
3     [0, 0]  [0, 0]    [79, 40]  [125, 140]    [61, 85]     [40, 79]
4     [1, 0]  [1, 0]    [20, 38]    [88, 50]    [30, 50]     [38, 20]
...      ...     ...         ...         ...         ...          ...
5438  [1, 0]  [0, 0]    [32, 60]  [117, 115]    [83, 57]     [60, 32]
5439  [0, 0]  [0, 0]   [68, 125]  [333, 250]  [182, 208]    [125, 68]
5440  [0, 1]  [0, 0]    [49, 86]  [199, 105]   [56, 113]     [86, 49]
5441  [1, 0]  [0, 0]    [30, 34]    [82, 63]    [33, 48]     [34, 30]
5442  [0, 0]  [0, 1]    [45, 44]   [80, 103]    [58, 36]     [44, 45]

     total_str_abs total_str_att total_str_def total_str_land   td_att td_land
0         [83, 64]    [162, 170]      [87, 98]       [64, 83]   [3, 0]  [1, 0]
1         [34, 57]     [111, 70]      [36, 54]       [57, 34]   [0, 9]  [0, 6]
2          [9, 81]     [139, 39]      [30, 58]        [81, 9]   [7, 0]  [4, 0]
3        [155, 76]    [161, 224]      [69, 85]      [76, 155]   [0, 9]  [0, 2]
4         [51, 74]     [127, 88]      [37, 53]       [74, 51]  [1, 11]  [0, 2]
...            ...           ...           ...            ...      ...     ...
5438      [37, 71]    [130, 121]      [84, 59]       [71, 37]   [5, 0]  [2, 0]
5439     [68, 127]    [335, 250]    [182, 208]      [127, 68]   [0, 1]  [0, 0]
5440      [53, 93]    [206, 109]     [56, 113]       [93, 53]   [5, 0]  [2, 0]
5441      [53, 70]     [120, 90]      [37, 50]       [70, 53]  [1, 11]  [1, 4]
5442    [103, 115]    [157, 169]      [66, 42]     [115, 103]  [11, 1]  [4, 0]

[5443 rows x 15 columns]>

In [435]:
fighter_1 = []
fighter_2 = []

fighter_1_kd = []
fighter_2_kd = []

fighter_1_nsub = []
fighter_2_nsub = []

fighter_1_sig_str_abs = []
fighter_2_sig_str_abs = []

fighter_1_sig_str_att =[]
fighter_2_sig_str_att =[]

fighter_1_sig_str_def = []
fighter_2_sig_str_def = []

fighter_1_sig_str_land = []
fighter_2_sig_str_land = []

fighter_1_tot_str_abs = []
fighter_2_tot_str_abs = []

fighter_1_tot_str_att = []
fighter_2_tot_str_att = []

fighter_1_tot_str_def = []
fighter_2_tot_str_def = []

fighter_1_tot_str_land = []
fighter_2_tot_str_land = []

fighter_1_td_att = []
fighter_2_td_att = []

fighter_1_td_land = []
fighter_2_td_land = []

In [408]:
new = bout_detail_df["kd"]
new = new[0][0]
new

0

In [431]:
new = bout_detail_df["kd"].astype('string')

new = new[0].split("[")
new = new[1].split("]")
new = new[0].split(",")
new

['0', ' 0']

In [436]:
new = bout_detail_df["fighter_name"]

for i in new:
    
    fighter_1_nm = i[0]
    fighter_2_nm = i[1]
    
    fighter_1.append(fighter_1_nm)
    fighter_2.append(fighter_2_nm)
    

    
for i in bout_detail_df["kd"]:
    
    i = bout_detail_df["kd"].astype('string')

    i = i[0].split("[")
    i = i[1].split("]")
    i = i[0].split(",")
    
    f1_kd = int(i[0])
    f2_kd = int(i[1])
    
    fighter_1_kd.append(f1_kd)
    fighter_2_kd.append(f2_kd)
    
for i in bout_detail_df["n_sub"]:
    
    i = bout_detail_df["n_sub"].astype('string')

    i = i[0].split("[")
    i = i[1].split("]")
    i = i[0].split(",")

    f1_nsub = int(i[0])
    f2_nsub = int(i[1])
    
    fighter_1_nsub.append(f1_nsub)
    fighter_2_nsub.append(f2_nsub)
    
for i in bout_detail_df["sig_str_abs"]:
    
    i = bout_detail_df["sig_str_abs"].astype('string')

    i = i[0].split("[")
    i = i[1].split("]")
    i = i[0].split(",")
    
    f1_sig_abs = int(i[0])
    f2_sig_abs = int(i[1])
    
    fighter_1_sig_str_abs.append(f1_sig_abs)
    fighter_2_sig_str_abs.append(f2_sig_abs)
    
for i in bout_detail_df["sig_str_att"]:
    
    i = bout_detail_df["sig_str_att"].astype('string')

    i = i[0].split("[")
    i = i[1].split("]")
    i = i[0].split(",")
    
    f1_sig_att = int(i[0])
    f2_sig_att = int(i[1])
    
    fighter_1_sig_str_att.append(f1_sig_att)
    fighter_2_sig_str_att.append(f2_sig_att)
    
for i in bout_detail_df["sig_str_def"]:
    
    i = bout_detail_df["sig_str_def"].astype('string')

    i = i[0].split("[")
    i = i[1].split("]")
    i = i[0].split(",")
    
    f1_sig_def = int(i[0])
    f2_sig_def = int(i[1])
    
    fighter_1_sig_str_def.append(f1_sig_def)
    fighter_2_sig_str_def.append(f2_sig_def)
    
for i in bout_detail_df["sig_str_land"]:
    
    i = bout_detail_df["sig_str_land"].astype('string')

    i = i[0].split("[")
    i = i[1].split("]")
    i = i[0].split(",")
    
    f1_sig_land = int(i[0])
    f2_sig_land = int(i[1])
    
    fighter_1_sig_str_land.append(f1_sig_land)
    fighter_2_sig_str_land.append(f2_sig_land)
    
for i in bout_detail_df["total_str_abs"]:
    
    i = bout_detail_df["total_str_abs"].astype('string')

    i = i[0].split("[")
    i = i[1].split("]")
    i = i[0].split(",")
    
    f1_tot_abs = int(i[0])
    f2_tot_abs = int(i[1])
    
    fighter_1_tot_str_abs.append(f1_tot_abs)
    fighter_2_tot_str_abs.append(f2_tot_abs)
    
for i in bout_detail_df["total_str_att"]:
    
    i = bout_detail_df["total_str_att"].astype('string')

    i = i[0].split("[")
    i = i[1].split("]")
    i = i[0].split(",")
    
    f1_tot_att = int(i[0])
    f2_tot_att = int(i[1])
    
    fighter_1_tot_str_att.append(f1_tot_att)
    fighter_2_tot_str_att.append(f2_tot_att)
    
for i in bout_detail_df["total_str_def"]:
    
    i = bout_detail_df["total_str_def"].astype('string')

    i = i[0].split("[")
    i = i[1].split("]")
    i = i[0].split(",")
    
    f1_tot_def = int(i[0])
    f2_tot_def = int(i[1])
    
    fighter_1_tot_str_def.append(f1_tot_def)
    fighter_2_tot_str_def.append(f2_tot_def)
    
for i in bout_detail_df["total_str_land"]:
    
    i = bout_detail_df["total_str_land"].astype('string')

    i = i[0].split("[")
    i = i[1].split("]")
    i = i[0].split(",")
    
    f1_tot_land = int(i[0])
    f2_tot_land = int(i[1])
    
    fighter_1_tot_str_land.append(f1_tot_land)
    fighter_2_tot_str_land.append(f2_tot_land)
    
for i in bout_detail_df["td_att"]:
    
    i = bout_detail_df["td_att"].astype('string')

    i = i[0].split("[")
    i = i[1].split("]")
    i = i[0].split(",")
    
    f1_td_att = int(i[0])
    f2_td_att = int(i[1])
    
    fighter_1_td_att.append(f1_td_att)
    fighter_2_td_att.append(f2_td_att)
    
for i in bout_detail_df["td_land"]:
    
    i = bout_detail_df["td_land"].astype('string')

    i = i[0].split("[")
    i = i[1].split("]")
    i = i[0].split(",")
    
    f1_td_land = int(i[0])
    f2_td_land = int(i[1])
    
    fighter_1_td_land.append(f1_td_land)
    fighter_2_td_land.append(f2_td_land)

In [437]:
fight_id = bout_detail_df["fight_id"]
outcome = bout_detail_df["fighter_status"]

In [438]:
split_bout = pd.DataFrame({"fight_id": fight_id, 
                           "result": outcome, 
                           "fighter_1": fighter_1,
                           "fighter_1_kd": fighter_1_kd, 
                           "fighter_1_nsub": fighter_1_nsub,
                           "fighter_1_sig_abs": fighter_1_sig_str_abs,
                           "fighter_1_sig_att": fighter_1_sig_str_att,
                           "fighter_1_sig_def": fighter_1_sig_str_def,
                           "fighter_1_sig_land": fighter_1_sig_str_land,
                           "fighter_2": fighter_2,
                           "fighter_2_kd": fighter_2_kd, 
                           "fighter_2_nsub": fighter_2_nsub,
                           "fighter_2_sig_abs": fighter_2_sig_str_abs,
                           "fighter_2_sig_att": fighter_2_sig_str_att,
                           "fighter_2_sig_def": fighter_2_sig_str_def,
                           "fighter_2_sig_land": fighter_2_sig_str_land
                          })

In [439]:
split_bout

,fight_id,result,fighter_1,fighter_1_kd,fighter_1_nsub,fighter_1_sig_abs,fighter_1_sig_att,fighter_1_sig_def,fighter_1_sig_land,fighter_2,fighter_2_kd,fighter_2_nsub,fighter_2_sig_abs,fighter_2_sig_att,fighter_2_sig_def,fighter_2_sig_land
0,d7cbe2f23d75afd1,"[L, W]",Julio Arce,0,0,55,124,84,32,Hakeem Dawodu,0,0,32,139,92,55
1,f0418c2c989a5cde,"[L, W]",Grigorii Popov,0,0,55,124,84,32,Davey Grant,0,0,32,139,92,55
2,fc16ccf0994c6e50,"[W, L]",Jack Shore,0,0,55,124,84,32,Nohelin Hernandez,0,0,32,139,92,55
3,18e1b0df8da7010e,"[L, W]",Vanessa Melo,0,0,55,124,84,32,Tracy Cortez,0,0,32,139,92,55
4,57ff0eb2351979c4,"[W, L]",Khalid Taha,0,0,55,124,84,32,Bruno Silva,0,0,32,139,92,55
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5438,953c89aa931082e4,"[W, L]",Jose Quinonez,0,0,55,124,84,32,Carlos Huachin,0,0,32,139,92,55
5439,c163ed45c21c8548,"[W, L]",Irene Aldana,0,0,55,124,84,32,Vanessa Melo,0,0,32,139,92,55
5440,49b2a6a93d529981,"[L, W]",Martin Bravo,0,0,55,124,84,32,Steven Peterson,0,0,32,139,92,55
5441,fd3e8f61d8fda839,"[D, D]",Brandon Moreno,0,0,55,124,84,32,Askar Askarov,0,0,32,139,92,55
5442,b2cdb4c34f37ad37,"[W, L]",Carla Esparza,0,0,55,124,84,32,Alexa Grasso,0,0,32,139,92,55

In [502]:
joined_bout = split_bout.join(bout_df.set_index("fight_id"), how="inner", on="fight_id")
joined_bout["date"] = joined_bout["date"].astype("int")
joined_bout.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4753 entries, 0 to 5442
Data columns (total 24 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   fight_id                     4753 non-null   object
 1   result                       4753 non-null   object
 2   fighter_1                    4753 non-null   object
 3   fighter_1_kd                 4753 non-null   int64
 4   fighter_1_nsub               4753 non-null   int64
 5   fighter_1_sig_abs            4753 non-null   int64
 6   fighter_1_sig_att            4753 non-null   int64
 7   fighter_1_sig_def            4753 non-null   int64
 8   fighter_1_sig_land           4753 non-null   int64
 9   fighter_2                    4753 non-null   object
 10  fighter_2_kd                 4753 non-null   int64
 11  fighter_2_nsub               4753 non-null   int64
 12  fighter_2_sig_abs            4753 non-null   int64
 13  fighter_2_sig_att            4753 non-null   int64
 14  fighter_2_sig_def            4753 non-null   int64
 15  fighter_2_sig_land           4753 non-null   int64
 16  winner                       4753 non-null   object
 17  decision_method              4753 non-null   object
 18  fight_duration_lastrnd       4753 non-null   int64
 19  fight_duration_lastrnd_time  4753 non-null   object
 20  time_format                  4753 non-null   object
 21  weight_class                 4753 non-null   object
 22  date                         4753 non-null   int32
 23  fight_length_min             4753 non-null   float64
dtypes: float64(1), int32(1), int64(13), object(9)
memory usage: 909.8+ KB

In [501]:
from sqlalchemy import create_engine
engine = create_engine('postgresql+psycopg2://postgres:cdw@hostname/ufc')